### ISSUE TITLE
[SYNC] - Refine Structure of Sync Processor

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#236]
MW job: `[OMSBES1] omSupply Back End - Refine Structure of Sync Processor`

### Description

Chris provided us with a pretty good starting point, want to expand this to a more refined skeleton

### Scope

Sync structure in place:
<ins>Includes</ins>
* Relocate sync from main 
* Provide sync with handles to:
   * DB
   * Channel to send msgs
* Placeholders for sequence of actions sync needs to perform
   * I think we just want a mechanism to process things sequentially (i.e. try to pull central data, try to pull remote data, try to push sync q)  with choice of a given action happening on specific error type, )i.e. can't reach server, error integrating record)

<ins>Excludes</ins>
* Implementation of actual sync actions
* Specifying all of the actions that need to happen and their sequence
* Implementation of cursor handling or any DB actions

### Tasks
- [x] MW job added
- [x] https://github.com/openmsupply/remote-server/issues/234
- [x] https://github.com/openmsupply/remote-server/issues/215
- [x] https://github.com/openmsupply/remote-server/issues/240

**Comment by wlthomson** [comment]
@andreievg I'm still adding work under this to the rust prototype job, can we get this job made soonish?

**Comment by wlthomson** [comment]
Closing as all tasks completed!
