### ISSUE TITLE
M2

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#515]
### Sessions And Auth
- [ ] Login/Logout  https://github.com/openmsupply/remote-server/issues/506
- [ ] Tokens https://github.com/openmsupply/remote-server/issues/506
- [ ] Filter by logged in store id
- [ ] Auth errors (all queries and mutations)

### Invoice Numbering
- [ ] Use existing mSupply mechanism https://github.com/openmsupply/remote-server/issues/514
- [ ] ~~Number re-use~~ (pushed)

### Expand Items/Name/Stores queries
- [x] Discussion to determine which fields are added, based on: https://github.com/openmsupply/remote-server/issues/513 (also for name and store)
- [ ] Add extra fields to item name and store schema and query + sync
- [ ] Expose aggregate fields on item -> stock on hand, ~~amc, mos~~ (pushed)

### Documentation
- [ ] Generate DB schema docs https://github.com/openmsupply/remote-server/issues/230
- [ ] Further comments in API
- [ ] Zola docs update (including architecture so far, and restructure)

### Requisitions
- [ ] Just requisitions themselves without lines

### Term Alignment
- [x] Rename 'type' of invoices to align with front end (SI -> Inbound Shipment, CI -> Outbound Shipment).

### Batched mutations alternative
- [x] https://github.com/openmsupply/remote-server/issues/509

### Locations
- [ ] DB schema
- [ ] Queries
- [ ] Mutations

### Other API improvements
- [ ] https://github.com/openmsupply/remote-server/issues/512
- [ ] and any others

#### Security
* Safely store sync site credentials
* SSL
* Protocol selector for sync (in sync settings)

#### Benchmark
* Make sure we are on the right track (things work performant/async as expected)

#### Item Properties 
* Schema/Sync
* Filtering and fields exposed in API

#### Cross compilation
* Can we auto build for different platforms from say a docker container ?
* Tests (post build, and for different platforms), Bench.

#### Invoice status
* Align with Richard's statuses

**Comment by andreievg** [comment]
Most of this has been done, and others are duplicates or listed as bulletpoint in other issues
