### ISSUE TITLE
Handle Donors in shipments

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#584]
We've been asked to be able to assign the donor to an inbound shipment. The full requirements documentation is:

```
Donor - to assign a donor to the shipment (included in v1 ?)
```

As I see it, this would require
- [ ] Return donor field for invoice lines (#581)
- [ ] Ability to query for a list of donors (#583)
- [ ] Assign donor to an inbound shipment (#582)
- [ ] Return donor field on an outbound shipment (#580)

**Comment by mark-prins** [comment]
to do after requisitions, stocktakes and dashboard

**Comment by andreievg** [comment]
was wondering if this is in v1 ?

**Comment by mark-prins** [comment]
I think not - there's more important things to do
