### ISSUE TITLE
Requisitions and Transfers (Full Order Cycle)

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#703]
Related: https://github.com/openmsupply/remote-server/issues/625, https://github.com/openmsupply/remote-server/issues/624

### Tasks

* [x] - https://github.com/openmsupply/remote-server/issues/703
* [x] -  https://github.com/openmsupply/remote-server/issues/708
* [x] - https://github.com/openmsupply/remote-server/issues/710
* [x] -  https://github.com/openmsupply/remote-server/issues/712
* [x] - https://github.com/openmsupply/remote-server/issues/716
* [x] - https://github.com/openmsupply/remote-server/issues/718
* [x] - https://github.com/openmsupply/remote-server/issues/720
* [x] - https://github.com/openmsupply/remote-server/issues/722
* [x] - https://github.com/openmsupply/remote-server/issues/722
* [x] - https://github.com/openmsupply/remote-server/issues/724
* [x] - https://github.com/openmsupply/remote-server/issues/726
* [x] - https://github.com/openmsupply/remote-server/issues/728
* [x] - https://github.com/openmsupply/remote-server/issues/730
* [x] - https://github.com/openmsupply/remote-server/issues/732
* [x] - https://github.com/openmsupply/remote-server/issues/737
* [ ] - https://github.com/openmsupply/remote-server/issues/739
* ~~[Transfers](https://github.com/openmsupply/remote-server/issues/706) (Sync Processing Queue)~~
   * RequestRequisition <-> ResponseRequisition
   * OutboundShipment <-> InboundShipment

This issue summarises area of work that allows for complete order cycle.

### Order Cycle
[drive](https://app.diagrams.net/#G1Iq1kR4ZoxKOGZXqHz6K9p7-pH6-h63j0)
![Order Cycle](https://user-images.githubusercontent.com/26194949/150956728-78155212-3f43-4058-b90c-085c853a4b17.png)

### Graphql Schema 

See issue and pr

#### Requisition

| mSupply                      | omSupply                  |                                                                         |
|------------------------------|---------------------------|-------------------------------------------------------------------------|
| date_entered                 |                           | if no om_created_datetime present use this to populate created_datetime |
| (new) om_created_datetime    | created_datetime          | also translates to date_entered in sync                                 |
| (new) om_sent_datetime       | sent_datetime             |                                                                         |
| (new) om_finalised_datetime  | finalised_datetime        |                                                                         |
| serial_number                | requisition_number        |                                                                         |
| thresholdMOS                 | threshold_months_of_stock |                                                                         |
| daystoSupply                 |                           | if no om_max_months_of_stock use this one (divide by 30)                |
| (new) om_max_months_of_stock | max_months_of_stock       | also translates to daysToSupply in sync                                 |
| requester_reference          | their_reference           |                                                                         |
| status                       |                           | see below                                                               |
| (new_ om_status              | status                    | see below (translated to mStatus in sync)                               |

#### Requisition Status

| mSupply                      | omSupply                  |                                                                                                                   |
|------------------------------|---------------------------|-------------------------------------------------------------------------------------------------------------------|
| sg                           | Draft                     | Request Requisition only (Draft = manually created, New = generated)                                              |
| cn                           | New                       | Response Requisition only                                                                                         |
| fn                           | Sent                      | Request Requisition only (not editable)                                                                           |
| fn                           | Finalised                 | Response and Request requisition (when Response requisition is fully supplied, also updates request requisition)  |

#### Requisition Type

Still Request and Response, also mutations are named RequestRequisition and ResponseRequisition (couldn't really find a better term, and some what consistent with invoice, where type is in the mutation name)

#### Requisition Line

| mSupply                         | omSupply                             |                                                                         |
|---------------------------------|--------------------------------------|-------------------------------------------------------------------------|
| cust_stock_order                | requested_quantity                   |                                                                         |
| actualQuan                      | supply_quantity                      | Editable and visible in Response Requisition only                       |
| suggested_quantity              | calculated_quantity                  |                                                                         |
| stock_on_hand                   | request_stock_on_hand                |                                                                         |
| daily_usage                     |                                      | If request_average_monthly_consumption is not present use this one * 30 |
| (new) om_request_amc            | request_average_monthly_consumption  | Translates to daily_usage in sync                                       |
| (new) om_response_stock_on_hand | response_stock_on_hand               | Visible in Response Requisition only                                    |
| (new) om_response_amc           | response_average_monthly_consumption | Visible in Response Requisition only                                    |

You will notice differentiation between request and response, since item stats are available in both requisition types, wanted to differentiate which stat refers to what, also they are snapshots (wanted to record those figures at the time the order was created). Was even thinking of refresh stats endpoint to refresh them, hmm.

### Links

Contrary to what i've communicated in our meeting on 25th, i removed denormalised fields on requisition line and decided to go with:

`RequisitionLineNode`

inboundShipmentLines -> InvoiceLineConnector
outboundShipmentLines -> InvoiceLineConnector

this way any information can be displayed when looking at requisition edit/view page (not worrying about fulfilment status of the whole requisition for now)

`Requisition`

shipments -> InvoiceNodeConnector (Inbound/Outbound for Request/Response respectively)

### Sync Processor Queue

Is just something that I came up with for creating transfers etc.. I think it would work nicely with sync, will write further description in the issue
