### ISSUE TITLE
Refactor/Alignments/Docs

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#749]
Want to apply latest patterns consistently in the codebase and have solid docs (pre requisite of V1 release)

## Repositories

- [ ] Rename repositories (i.e. when we have [Type]Query to [Type] and [Type]Row
- [x] https://github.com/openmsupply/remote-server/issues/832
- [x] https://github.com/openmsupply/remote-server/issues/822
- [ ] upsert_many (see draft PR)
- [ ] one file for schema definition (see draft https://github.com/openmsupply/remote-server/pull/797)

### Graphql
- [x] https://github.com/openmsupply/remote-server/issues/849
- [x] https://github.com/openmsupply/remote-server/issues/638
- [x] https://github.com/openmsupply/remote-server/issues/699
- [x] https://github.com/openmsupply/remote-server/issues/781
- [x] Remove `graphql_client` from tests
- [ ] remove invoice_id from line mutations

### Service
- [x] Use service provider
- [ ] All service validate methods to map_err
- [x] https://github.com/openmsupply/remote-server/issues/850
- [ ] https://github.com/openmsupply/remote-server/issues/460 (might be done already ?)
- [x] https://github.com/openmsupply/remote-server/issues/739
- [ ] https://github.com/openmsupply/remote-server/issues/762
- [x] https://github.com/openmsupply/remote-server/issues/757

** Docs
- [ ] https://github.com/openmsupply/remote-server/issues/230
- [ ] Update all graphql resolvers with comments
- [ ] Update docs with patterns and shared diagrams
- [ ] Update api docs
- [ ] How to add new end point with mutations
- [ ] How to add new sync record
- [ ] Maybe (as this would be quite a bit of work) https://github.com/openmsupply/remote-server/issues/504

**Comment by andreievg** [comment]
Closing, cary over is in https://github.com/openmsupply/remote-server/issues/993 and https://github.com/openmsupply/remote-server/issues/994
