### ISSUE TITLE
Api Change Requests f/e #827

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#805]
Epic to group change requests from: https://github.com/openmsupply/openmsupply-client/issues/827, that don't have an issue.

- [x] https://github.com/openmsupply/remote-server/issues/799
- [x] https://github.com/openmsupply/remote-server/issues/800
- [x] https://github.com/openmsupply/remote-server/issues/801
- [x] https://github.com/openmsupply/remote-server/issues/802
- [x] https://github.com/openmsupply/remote-server/issues/803
- [x] https://github.com/openmsupply/remote-server/issues/804
- [x] https://github.com/openmsupply/remote-server/issues/806
- [x] https://github.com/openmsupply/remote-server/issues/807
- [x] https://github.com/openmsupply/remote-server/issues/808
- [ ] https://github.com/openmsupply/remote-server/issues/809
- [x] https://github.com/openmsupply/remote-server/issues/870
- [x] https://github.com/openmsupply/remote-server/issues/872
- [x] https://github.com/openmsupply/remote-server/issues/846
- [x] https://github.com/openmsupply/remote-server/pull/876

**Comment by andreievg** [comment]
Closing, requisition charts still not finished but it has it's own epic, will create new issue to group future changes (issue per week)
