### ISSUE TITLE
Internal documentation for V1

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#993]
We are way behind documentation for sync, schema, api, project structure, etc.. 

- [ ] https://github.com/openmsupply/remote-server/issues/230
- [ ] https://github.com/openmsupply/remote-server/issues/206
- [ ] Update api documentation
- [ ] General architecture
- [ ] Folder structure
- [ ] HowTo 
   - [ ] How to add new end point
   - [ ] How to add new table and query
   - [ ] How to add new mutation
