### ISSUE TITLE
Improvements V1

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#994]
Carry over from (https://github.com/openmsupply/remote-server/issues/749)

- [ ] Rename repositories (i.e. when we have [Type]Query to [Type] and [Type]Row
- [ ] one file for schema definition (see draft https://github.com/openmsupply/remote-server/pull/797)
- [ ] remove invoice_id from line mutations
- [ ] All service validate methods to map_err
- [ ] https://github.com/openmsupply/remote-server/issues/460
- [ ] https://github.com/openmsupply/remote-server/issues/762
