### ISSUE TITLE
Stocktake remainder

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#997]
- [ ] https://github.com/openmsupply/remote-server/issues/895
- [ ] https://github.com/openmsupply/remote-server/issues/888
- [ ] https://github.com/openmsupply/remote-server/issues/981
